volumes:
  
  postgres-data:
    driver: local
  
  seq-data:
    driver: local

services:
  
  nginx:
    container_name: "nginx"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Certificates/artisan.crt:/etc/nginx/cert.crt:ro
      - ./Certificates/artisan.rsa:/etc/nginx/cert.rsa:ro
    ports:
      - 80:80
      - 443:443
  
  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  
  seq:
    container_name: "seq"
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - seq.env
    volumes:
      - ./Certificates/artisan.pfx:/data/Certificates/443.pfx
      - seq-data:/data/

  artisan.server:
    container_name: "app"
    image: artisan.server
    volumes:
      - ./Certificates/artisan.pfx:/app/artisan.pfx:ro 
    env_file:
      - app.env
    build:
      context: .
      dockerfile: Dockerfile
