volumes:
  
  postgres-data:
    driver: local
  
  seq-data:
    driver: local

services:
  
  postgres:
    container_name: "postgres"
    image: postgres
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 20002:5432
  
  seq:
    container_name: "seq"
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data/
    ports:
      - 20003:80

  artisan.server:
    container_name: "app"
    image: artisan.server
    env_file:
      - .env
    ports:
      - 20000:80
      - 20001:443
    build:
      context: .
      dockerfile: Dockerfile
